"""Stable reason codes — stored in the audit log, never renamed once shipped."""

from enum import StrEnum


class ReasonCode(StrEnum):
    # state / session
    STATE_NOT_ACTIVE = "STATE_NOT_ACTIVE"
    SESSION_CLOSED = "SESSION_CLOSED"
    ENTRY_CUTOFF = "ENTRY_CUTOFF"
    CRYPTO_WINDOW = "CRYPTO_WINDOW"
    # data trust
    STALE_QUOTE = "STALE_QUOTE"
    STALE_RECONCILE = "STALE_RECONCILE"
    CLOCK_SKEW = "CLOCK_SKEW"
    SUSPECT_QUOTE = "SUSPECT_QUOTE"
    # universe / direction
    NOT_IN_UNIVERSE = "NOT_IN_UNIVERSE"
    ADV_EXCEEDED = "ADV_EXCEEDED"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    SHORT_FORBIDDEN = "SHORT_FORBIDDEN"
    PHANTOM_POSITION = "PHANTOM_POSITION"
    # sizing
    ORDER_NOTIONAL_CAP = "ORDER_NOTIONAL_CAP"
    ORDER_SHARES_CAP = "ORDER_SHARES_CAP"
    MIN_NOTIONAL = "MIN_NOTIONAL"
    MARKET_ORDER_FORBIDDEN = "MARKET_ORDER_FORBIDDEN"
    PRICE_COLLAR_BREACH = "PRICE_COLLAR_BREACH"
    # exposure
    SYMBOL_EXPOSURE_CAP = "SYMBOL_EXPOSURE_CAP"
    GROSS_EXPOSURE_CAP = "GROSS_EXPOSURE_CAP"
    POSITION_COUNT_CAP = "POSITION_COUNT_CAP"
    CRYPTO_SLEEVE_CAP = "CRYPTO_SLEEVE_CAP"
    SLEEVE_BUDGET_EXCEEDED = "SLEEVE_BUDGET_EXCEEDED"
    SLEEVE_ORDER_CAP = "SLEEVE_ORDER_CAP"
    # anti-runaway
    DUPLICATE_WINDOW = "DUPLICATE_WINDOW"
    OPEN_ENTRY_EXISTS = "OPEN_ENTRY_EXISTS"
    RATE_GLOBAL_MIN = "RATE_GLOBAL_MIN"
    RATE_GLOBAL_DAY = "RATE_GLOBAL_DAY"
    RATE_SYMBOL_MIN = "RATE_SYMBOL_MIN"
    RATE_SYMBOL_DAY = "RATE_SYMBOL_DAY"
    # breakers / transitions
    DAILY_LOSS = "DAILY_LOSS"
    DRAWDOWN_WARN = "DRAWDOWN_WARN"
    DRAWDOWN_HALT = "DRAWDOWN_HALT"
    CONSECUTIVE_LOSSES = "CONSECUTIVE_LOSSES"
    SYMBOL_COOLDOWN = "SYMBOL_COOLDOWN"
    REJECTION_STORM = "REJECTION_STORM"
    RECONCILE_MISMATCH = "RECONCILE_MISMATCH"
    EXTERNAL_ORDER = "EXTERNAL_ORDER"
    KILL_SWITCH = "KILL_SWITCH"
    STARTUP = "STARTUP"
    OPERATOR = "OPERATOR"
    COOL_OFF_EXPIRED = "COOL_OFF_EXPIRED"
